name: flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  audio_service: ^0.18.18
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  go_router: ^17.0.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^3.1.0
  http: ^1.6.0
  intl: ^0.20.2
  just_audio: ^0.10.5
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
